[package]
name = "trustedvoted"
version = "0.1.0"
authors = ["Trusted Vote Contributors"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
